apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: web-blog
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: web-blog
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50